version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    groups:
      non-major:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
